# Generated by Django 3.0.1 on 2020-12-19 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128)),
                ('enrolled_in', models.DateField()),
                ('finished_in', models.DateField()),
                ('position_holding', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.TextField(max_length=500)),
                ('expiry_date', models.CharField(choices=[(1, None), (2, models.DateField())], max_length=200)),
                ('certificate', models.FileField(upload_to='Acievments/<django.db.models.fields.CharField>/')),
                ('certificate_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Higher_Secondary_Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year_of_pass_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Post_Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=120)),
                ('year_of_graduated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('technology_used', models.CharField(max_length=500)),
                ('framework_used', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(max_length=500)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year_of_pass_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Social_Site_Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField()),
                ('hackerrank', models.URLField()),
                ('linkedIn', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Under_Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=120)),
                ('year_of_graduated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_secondary_examination_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Higher_Secondary_Examination')),
                ('post_graduation_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Post_Graduation')),
                ('secondary_examination_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Secondary_Examination')),
                ('under_graduation_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Under_Graduation')),
            ],
        ),
        migrations.CreateModel(
            name='MyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=10)),
                ('tell_about_me_your_self', models.TextField(max_length=500)),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('achievment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Achievment')),
                ('projects_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Project')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Qualification')),
                ('social_site_connection_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Social_Site_Connection')),
            ],
        ),
    ]
