# Generated by Django 3.0.1 on 2020-12-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydetail',
            name='profile_pic',
        ),
    ]
