# Generated by Django 3.0.1 on 2021-03-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydetail',
            name='achievment_details',
        ),
        migrations.RemoveField(
            model_name='mydetail',
            name='projects_detail',
        ),
        migrations.RemoveField(
            model_name='mydetail',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='mydetail',
            name='social_site_connection_details',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='higher_secondary_examination_details',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='post_graduation_details',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='secondary_examination_details',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='under_graduation_details',
        ),
        migrations.DeleteModel(
            name='Achievment',
        ),
        migrations.DeleteModel(
            name='Higher_Secondary_Examination',
        ),
        migrations.DeleteModel(
            name='MyDetail',
        ),
        migrations.DeleteModel(
            name='Post_Graduation',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Secondary_Examination',
        ),
        migrations.DeleteModel(
            name='Social_Site_Connection',
        ),
        migrations.DeleteModel(
            name='Under_Graduation',
        ),
    ]
