# Generated by Django 3.0.1 on 2021-03-26 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Portfolio', '0002_auto_20210326_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128)),
                ('enrolled_in', models.DateField()),
                ('finished_in', models.DateField()),
                ('position_holding', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.TextField(max_length=500)),
                ('expiry_date', models.CharField(choices=[('1', 'none')], max_length=200)),
                ('certificate', models.FileField(upload_to='Acievments/')),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Higher_Secondary_Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year_of_pass_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OptionalPic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=120)),
                ('year_of_graduated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year_of_pass_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Under_Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=120)),
                ('year_of_graduated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Social_Site_Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField()),
                ('hackerrank', models.URLField()),
                ('linkedIn', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_secondary_examination_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Higher_Secondary_Examination')),
                ('post_graduation_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Post_Graduation')),
                ('secondary_examination_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Secondary_Examination')),
                ('under_graduation_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Under_Graduation')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('technology_used', models.CharField(max_length=500)),
                ('framework_used', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(max_length=500)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tell_about_me_your_self', models.TextField(max_length=500)),
                ('profile_pic', models.ImageField(default='', upload_to='media/images/')),
                ('achievment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Achievment')),
                ('optional_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Pics')),
                ('projects_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Project')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Qualification')),
                ('social_site_connection_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Social_Site_Connection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
