# Generated by Django 3.0.1 on 2020-12-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_remove_mydetail_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
