# Generated by Django 3.0.1 on 2020-12-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_mydetail_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='expiry_date',
            field=models.CharField(choices=[(1, 'none'), (2, models.DateField())], max_length=200),
        ),
    ]
