# Generated by Django 3.0.1 on 2021-03-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_achievment_higher_secondary_examination_mydetail_pics_post_graduation_project_qualification_secondar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='alternative_text',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pics',
            name='alternative_text',
            field=models.CharField(default='', max_length=40),
        ),
    ]
