# Generated by Django 3.0.1 on 2020-12-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_auto_20201220_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='expiry_date',
            field=models.TextField(choices=[('1', 'none'), ('2', 'i need to enter date')], max_length=200),
        ),
    ]
