# Generated by Django 3.0.1 on 2021-03-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_remove_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='github_link',
        ),
        migrations.AddField(
            model_name='project',
            name='web_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
