# Generated by Django 3.0.1 on 2021-03-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_auto_20210331_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='Resume/'),
        ),
    ]
