# Generated by Django 3.0.1 on 2020-12-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_auto_20201220_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='certificate',
            field=models.FileField(upload_to='Acievments/<django.db.models.fields.TextField>/'),
        ),
        migrations.AlterField(
            model_name='achievment',
            name='event_name',
            field=models.TextField(max_length=128),
        ),
    ]
