# Generated by Django 3.0.1 on 2020-12-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0008_auto_20201220_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='certificate',
            field=models.FileField(upload_to='Acievments/'),
        ),
        migrations.AlterField(
            model_name='achievment',
            name='event_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='achievment',
            name='expiry_date',
            field=models.CharField(choices=[('1', 'none')], max_length=200),
        ),
    ]
