# Generated by Django 3.0.1 on 2020-12-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0009_auto_20201220_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='media/images/'),
        ),
    ]
