# Generated by Django 3.0.1 on 2021-04-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0009_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_site_connection',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='social_site_connection',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='social_site_connection',
            name='stack_overflow',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social_site_connection',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='social_site_connection',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social_site_connection',
            name='hackerrank',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social_site_connection',
            name='linkedIn',
            field=models.URLField(blank=True, null=True),
        ),
    ]
