# Generated by Django 3.0.1 on 2021-04-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0011_auto_20210406_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_site_connection',
            name='email',
        ),
    ]
