# Generated by Django 3.0.1 on 2021-04-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0012_remove_social_site_connection_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='higher_secondary_examination_details',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='post_graduation_details',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='secondary_examination_details',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='under_graduation_details',
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='pics',
            options={'verbose_name_plural': 'Pics'},
        ),
        migrations.AlterModelOptions(
            name='social_site_connection',
            options={'verbose_name_plural': 'Social Site Connections'},
        ),
        migrations.RemoveField(
            model_name='mydetail',
            name='qualification',
        ),
        migrations.DeleteModel(
            name='Higher_Secondary_Examination',
        ),
        migrations.DeleteModel(
            name='Post_Graduation',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Secondary_Examination',
        ),
        migrations.DeleteModel(
            name='Under_Graduation',
        ),
    ]
