# Generated by Django 3.0.1 on 2021-04-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0016_auto_20210407_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='contact_number',
            field=models.CharField(default='', max_length=12),
        ),
    ]
