# Generated by Django 3.0.1 on 2021-04-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0017_mydetail_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='contact_number',
            field=models.CharField(default='', max_length=13),
        ),
    ]
