# Generated by Django 3.0.1 on 2021-04-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0019_auto_20210407_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='contact_number',
            field=models.CharField(default='', help_text='(Hint) add spaces for format the number as mine', max_length=16),
        ),
    ]
