# Generated by Django 3.0.1 on 2021-04-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0020_auto_20210407_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
