# Generated by Django 3.0.1 on 2021-04-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0021_mydetail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', editable=False),
        ),
    ]
