# Generated by Django 3.0.1 on 2021-04-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0022_mydetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='url',
            field=models.URLField(default='', editable=False),
        ),
    ]
