# Generated by Django 3.0.1 on 2021-04-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0024_auto_20210409_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='optional_alternative_text',
            field=models.CharField(default='about-my-image', editable=False, max_length=40),
        ),
    ]
