# Generated by Django 3.0.1 on 2021-04-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0025_auto_20210409_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mailbackend',
            options={'verbose_name_plural': 'Mail Backend'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology_used',
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used',
            field=models.TextField(blank=True, help_text="like Databases,Front-End,API's etc", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='language_used',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Language'),
        ),
    ]
