# Generated by Django 3.0.1 on 2021-04-11 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Portfolio', '0029_auto_20210411_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievment',
            unique_together={('user', 'event_name')},
        ),
    ]
