# Generated by Django 3.0.1 on 2021-04-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0030_auto_20210411_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydetail',
            name='url',
        ),
        migrations.AddField(
            model_name='mydetail',
            name='profession',
            field=models.CharField(default='', help_text='Example: Front-End Developer, Back-End Developer etc.', max_length=50),
        ),
    ]
