# Generated by Django 3.0.1 on 2021-04-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0031_auto_20210413_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='url',
            field=models.URLField(default='', editable=False, verbose_name='Site URL'),
        ),
    ]
