# Generated by Django 3.0.1 on 2021-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0034_auto_20210413_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='visited',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
