# Generated by Django 3.0.1 on 2021-04-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0035_mydetail_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
