# Generated by Django 3.0.1 on 2021-04-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0036_auto_20210413_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydetail',
            name='optional_alternative_text',
        ),
        migrations.RemoveField(
            model_name='mydetail',
            name='profile_alternative_text',
        ),
        migrations.AlterField(
            model_name='mydetail',
            name='achievment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Achievment'),
        ),
    ]
