# Generated by Django 3.0.1 on 2021-04-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0037_auto_20210413_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydetail',
            old_name='achievment_details',
            new_name='achievement_details',
        ),
    ]
