# Generated by Django 3.0.1 on 2021-04-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0038_auto_20210422_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='', help_text='Please Add less than 100 characters, else rest of the text automatically hide.', verbose_name='little Description'),
        ),
    ]
