# Generated by Django 3.0.1 on 2021-04-30 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0040_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
