# Generated by Django 3.0.1 on 2021-05-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0041_subscribe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(blank=True, help_text='Please enter only color codes or name, do not include rgba values', max_length=20, null=True, verbose_name='background color'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
